import { connection } from "next/server";

/**
 * Forces the unlock page into dynamic rendering so the CSP nonce generated by
 * the middleware actually reaches Next.js's HTML emitter. Without this, the
 * client-component page is prerendered at build time and the bootstrap scripts
 * ship without a nonce — 'strict-dynamic' then refuses to hydrate them.
 */
export default async function UnlockLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  await connection();
  return <>{children}</>;
}
